test_project/credentials/urls.py
from django.urls import path
from .import views
app_name='credentials'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/',views.register, name='register'),
    path('logout/',views.logout,name='logout'),
    path('update/<int:id>/',views.update,name='update_user'),
    path('delete/<int:id>/',views.delete,name='delete_user'),
    path('add/>/',views.add,name='add_user'),
    path('search/', views.SearchResult, name='SearchResult'),
    path('adminlogin/',views.admin_login, name='admin_login'),
    path('admin/',views.admin, name='admin')
]

test_project/test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web_main.urls')),
    path('accounts/',include('credentials.urls', namespace="credentials"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

test_project/web_main/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('home/',views.home, name='home'),
    path('',views.welcome_page,name='welcome_page')
]

test_project/credentials/models.py
from django.db import models

# Create your models here.

test_project/web_main/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=100, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='products', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    stock=models.IntegerField()

    def __str__(self):
        return '{}'.format(self.product_name)

test_project/credentials/forms.py
from django.contrib.auth.models import User
from django import forms
from django.urls import reverse_lazy

class Accountform(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        success_url = reverse_lazy('admin')

test_project/credentials/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.models import User,auth
from django.views.decorators.cache import cache_control
from .forms import Accountform
from django.db.models import Q


# Create your views here.
# login view function for user
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login(request):
    if 'user' in request.session:
        return redirect('home')

    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']

        user = auth.authenticate(username=username,password=password)

        if user is not None:
            request.session['user'] = username
            auth.login(request,user)
            response = redirect('home')
            response.set_cookie('username',username)
            response.set_cookie('logged_in', True)
            return response
        else:
            messages.info(request, 'Invalid credentials')
            return redirect('credentials:login')
    else:
        return render(request, 'login.html')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_login(request):
    if 'super' in request.session:
        return redirect('credentials:admin')
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']

        user = auth.authenticate(username=username,password=password)
        s = user.is_superuser
        if s:
            request.session['super'] = username
            request.session['user']=username
            auth.login(request, user)
            response = redirect('credentials:admin')
            response.set_cookie('username', username)
            response.set_cookie('logged_in', True)
            return response
        else:
            return redirect('welcome_page')
    else:
        return render(request, 'adminlogin.html')

#  view function for registration
def register(request):
    if request.method =='POST':
        first_name=request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username taken!')
                return redirect('credentials:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email taken!')
                return redirect('credentials:register')
            else:
                user = User.objects.create_user(username=username,first_name=first_name,last_name=last_name,password=password,email=email)
                user.save();
                return redirect('credentials:login')
        else:
            messages.info(request,"Password doesn't match!")
            return redirect('credentials:register')
    else:
        return render(request,'register.html')

#  view function for admin page
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin(request):
    if 'super' in request.session:
        users = User.objects.all().order_by('id')
        return render(request,'admin.html',{'users':users})
    return redirect('credentials:login')
#  view function for logging out
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout(request):
    response = redirect('credentials:login')
    if 'user' in request.session:
        response.delete_cookie('username')
        response.delete_cookie('logged_in')
        request.session.flush()
        auth.logout(request)
    return response


#  view function for user details updation
def update(request,id):
    if 'super' in request.session:
        add_user = User.objects.get(id=id)
        form = Accountform(request.POST or None, instance=add_user)
        if form.is_valid():
            form.save();
            return redirect('credentials:admin')
        return render(request,'update.html', {'form':form, 'add_user':add_user})
    return redirect('welcome_page')

#  view function for deleting a user
def delete(request,id):
    if 'super' in request.session:
        user = User.objects.get(id=id)
        if request.method=='POST':
            user.delete()
            return redirect('credentials:admin')
        return render(request,'delete.html')
    return redirect('welcome_page')

#  view function for adding a user from the admin page
def add(request):
    if 'super' in request.session:
        if request.method =='POST':
            username=request.POST.get('username', '')
            first_name = request.POST.get('first_name', '')
            last_name = request.POST.get('last_name', '')
            password=request.POST.get('password','')
            email=request.POST.get('email','')
            confirm_password=request.POST.get('confirm_password')
            if password==confirm_password:
                add_user=User.objects.create_user(username=username,first_name=first_name, last_name=last_name,email=email,password=password)
                add_user.save();
                return redirect('credentials:admin')
        return render(request, 'add.html')
    return redirect('welcome_page')

#  view function for searching user details
def SearchResult(request):
    if 'super' in request.session:
        users=None
        query=None
        if 'q' in request.GET:
            query=request.GET.get('q')
            users=User.objects.all().filter(Q(first_name__contains=query) | Q(last_name__contains=query) | Q(email__contains=query) | Q(username__contains=query))
            return render(request,'search.html', {'query': query, 'users': users})
    return redirect('welcome_page')

test_project/web_main/views.py
from django.shortcuts import render,redirect
from django.views.decorators.cache import cache_control

from .models import Product
# Create your views here.

# view function for home page
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def home(request):
    if 'user' in request.session:
        product = Product.objects.all()
        products = {'products': product}
        return render(request,'home.html', products)
    else:
        return redirect('credentials:login')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def welcome_page(request):
    request.session.flush()
    return render(request,'welcomepage.html')

test_project/templates/add.html
{% extends 'credentials_base.html' %}
{% load static %}
{% block content %}
<section>
  <div class="mt-4 mb-4"">
    <div class="container h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card text-white" style="border-radius: 1rem; background-color:black;" >
            <div class="card-body p-5">
                  <h2 class="  ml-3 mb-5">Create an User</h2>

                  <form method="post" class="mt-4 pl-0" id="signup-form">
                    {% csrf_token %}

                    <div class="form-outline ">
                      <label class="form-label" >Your First Name</label>
                      <input type="text" name="first_name" class="form-control form-control-lg" />

                    </div>
                    <div class="form-outline">
                      <label class="form-label" >Your Last Name</label>
                      <input type="text" name="last_name" class="form-control form-control-lg" />

                    </div>
                    <div class="form-outline">
                      <label class="form-label" >Username</label>
                      <input type="text" name="username" class="form-control form-control-lg" />

                    </div>

                    <div class="form-outline ">
                      <label class="form-label" >Your Email</label>
                      <input type="email" name="email" class="form-control form-control-lg" />

                    </div>

                    <div class="form-outline ">
                      <label class="form-label" >Password</label>
                      <input type="password" name="password" class="form-control form-control-lg" />

                    </div>

                    <div class="form-outline ">
                      <label class="form-label" >Repeat your password</label>
                      <input type="password" name="confirm_password" class="form-control form-control-lg" />

                    </div>

                    <div class=" justify-content-center mt-4 mb-5 pb-5">
                      <input type="submit" value="Create"
                        class="btn btn-dark btn-block btn-lg gradient-custom-7 text-body" style="background-color:black"/>
                    </div>


                  </form>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock  %}

test_project/templates/admin.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid d-flex justify-content-center mt-5 mx-0  ">

      <table class="table table-striped table-dark  " style="width:600px;">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>

          </tr>
        </thead>
        <tbody>
        {% for user in users %}
          <tr>
            <th scope="row">{{user.id}}</th>
            <td>{{ user.username}}</td>
            <td>{{ user.first_name}}</td>
            <td>{{ user.last_name}}</td>
            <td>{{ user.email}}</td>
            <td><a class="btn btn-danger" href="{% url 'credentials:delete_user' user.id %}">Delete</a>
            <td><a class="btn btn-warning" href="{% url 'credentials:update_user' user.id %}">Update</a> </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
</div>
<div class=" justify-content-center mt-0 ml-5 pl-5">
  <a href="{% url 'credentials:add_user' %}" class="btn  btn-success btn-block btn-lg gradient-custom-7 text-body" style=" width:665px; margin-left:340px;">CREATE USER </a>
</div>

{% endblock %}

test_project/templates/adminlogin.html
{% extends 'credentials_base.html' %}
{% load static %}
{% block content %}
<section class="vh-100 ">
  <div class="container py-5">
    <div class="row  justify-content-center  h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card  text-white" style="border-radius: 1rem; background-color:black;">
          <div class="card-body  p-5 ">

            <div class="mb-md-5 mt-md-4 pb-5 ">

                  <h2 class="fw-bold mb-2 ml-5 pl-3 text-uppercase">ADMIN SITE</h2>
                  <p class="text-white-50 mb-5 ml-3">Please enter your login and password!
               {% for message in messages %}
              <div class="border border-danger border-4 justify-content-center p-3 mb-3" style="background-color:#f1cdbc; height:52px;">
                <h6 class="text-dark pl-4 ml-5 ">{{message}}</h6>
              </div>
              {% endfor %}
              <form method="post" id="login-form" >
                  {% csrf_token %}
                  <div class="form-outline form-white mb-4">
                    <input type="text" name="username" class="form-control form-control-lg" />
                    <label class="form-label" >Username</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" name="password" class="form-control form-control-lg" />
                    <label class="form-label" >Password</label>
                  </div>

                  <button class="btn btn-outline-light btn-lg px-5 " style="margin-left:90px;" type="submit">Login</button>

    <!--              <div class="d-flex justify-content-center text-center mt-4 pt-1">-->
    <!--                <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>-->
    <!--                <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>-->
    <!--                <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>-->
    <!--              </div>-->
            </form>
            </div>

                  <div>
                    <p class="mb-0 ml-5">Don't have an account? <a href="{% url 'credentials:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                    </p>
                  </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock  %}

test_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
     <head>
          <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1">
           <!-- Bootstrap CSS -->
           <link rel="stylesheet"  type="text/css" href="{% static 'css/mainstyle.css' %}" >
           <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
          {% if title %}
          <title> blog {{'title'}}</title>
          {%else%}
          <title> blog-page </title>
          {% endif %}
         <style>
             .navbar{
                    margin:0 auto;
                    padding-left: 300px;
                    }
         </style>
     </head>
<body >
    <div class="container-fluid m-0 p-0">
            <nav class="navbar navbar-expand-sm justify-space-evenly " style="background-color:black;">
                  <div class="container-fluid">
                    <a class="navbar-brand" href="#" id="logo"><img src="{% static 'img/logo.png' %}" ></a>
                      {% if user.is_superuser %}
                        <button class=" btn btn-dark btn-outline-secondary ml-3 text-light" >USERS</button>
                        <button class=" btn btn-dark btn-outline-secondary ml-3 text-light" >PRODUCTS</button>
                      {% else %}
                        <button class=" btn btn-dark btn-outline-secondary ml-3 text-light" >PRODUCTS</button>
                      {% endif %}
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse " id="navbarSupportedContent">
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <form class="d-flex" action="{% url 'credentials:SearchResult' %}" method="get" role="search">
                                    <input class="form-control mr-2" type="search" placeholder="Search" name="q" aria-label="Search">
                                    <button class="btn btn-outline-success " type="submit">Search</button>
                                </form>
                                <a class="text-info ml-3 font-weight-bold" id="admin" href=""> Hi, {{user.username}} </a>
                                <a href="{% url 'credentials:logout' %}"><button class="btn btn-outline-secondary ml-3 text-light" type="submit">Log out</button></a>

                            {% else %}
                                <form class="d-flex" role="search">
                                    <input class="form-control mr-2" type="search" placeholder="Search"  aria-label="Search">
                                    <button class="btn btn-outline-success " type="submit">Search</button>
                                </form>
                                <a class="text-info ml-3 font-weight-bold" id="user" href=""> Hi, {{user.first_name}} </a>
                                <a href="{% url 'credentials:logout' %}"><button class="btn btn-outline-secondary ml-3 text-light" type="submit">Log out</button></a>

                            {% endif %}
                        {% else %}
                            <a href="{% url 'credentials:login' %}"><button class="btn btn-outline-secondary ml-3 text-light" type="submit">Log In</button></a>
                        {% endif %}
                    </div>
                  </div>
            </nav>
        {% block content %}
        {% endblock %}
    </div>
<!--    <div class="footer navbar-fixed-bottom my_footer" >-->
<!--        <p class="text-center">&copy; Heaven's Shop pvt ltd.All rights Reserved</p>-->
<!--    </div>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

test_project/templates/credentials_base.html
<!DOCTYPE html>
{% load static %}
<html>
     <head>
          <meta charset="utf-8">
          <meta http-equiv="X-UA-Compatible" content="IE=edge">
          <meta name="viewport" content="width=device-width, initial-scale=1">
           <!-- Bootstrap CSS -->
          <link rel="stylesheet"  type="text/css" href="{% static 'css/mainstyle.css' %}" >
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
          {% if title %}
          <title> blog {{'title'}}</title>
          {%else%}
          <title> blog-page </title>
          {% endif %}
         <style>
             .navbar{
                    margin:0 auto;
                    padding-left: 300px;
                    }
         </style>
     </head>
<body>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
<!--    <div class="footer navbar-fixed-bottom my_footer" >-->
<!--        <p class="text-center">&copy; Heaven's Shop pvt ltd.All rights Reserved</p>-->
<!--    </div>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

test_project/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<section>
  <div class="mt-4 mb-4"">
    <div class="container h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-4">
          <div class="card text-dark " style="border-radius: 1rem; background-color:#E0A96D; " >
            <div class="card-body p-5 ">
                <form  method="POST">
                    {% csrf_token %}
                    <p> Are you sure you want to delete the user {{user.username}}?</p>
                    <button  class="btn btn btn-outline-light btn-lg gradient-custom-7 text-body ml-5 mr-0" style=" background-color:black;" type="submit">Confirm</button>
                </form>
                 </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

test_project/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row justify-space-evenly mx-5 ">
        {% for product in products %}
            <div class="my-card col-sm-12 col-md-4 col-lg-3 mt-3">
                <div class="card text-center" style="min-width:18rem;">
                    <img class="card-img-top" src="{{product.image.url}}">
                    <div class="card-body">
                        <h4>{{product.product_name}}</h4>
                        <p>{{product.desc}}</p>
                        <h4>{{product.price}}</h4>
                     </div>
                 </div>
             </div>
        {% endfor %}
    </div>
{% endblock  %}

test_project/templates/login.html
{% extends 'credentials_base.html' %}
{% load static %}
{% block content %}
<section class="vh-100 ">
  <div class="container py-5">
    <div class="row  justify-content-center  h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card  text-white" style="border-radius: 1rem; background-color:black;">
          <div class="card-body  p-5 ">

            <div class="mb-md-5 mt-md-4 pb-5 ">

                  <h2 class="fw-bold mb-2 ml-5 pl-5 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5 ml-3">Please enter your login and password!
               {% for message in messages %}
              <div class="border border-danger border-4 justify-content-center p-3 mb-3" style="background-color:#f1cdbc; height:52px;">
                <h6 class="text-dark pl-4 ml-5 ">{{message}}</h6>
              </div>
              {% endfor %}
              <form method="post" id="login-form" >
                  {% csrf_token %}
                  <div class="form-outline form-white mb-4">
                    <input type="text" name="username" class="form-control form-control-lg" />
                    <label class="form-label" >Username</label>
                  </div>

                  <div class="form-outline form-white mb-4">
                    <input type="password" name="password" class="form-control form-control-lg" />
                    <label class="form-label" >Password</label>
                  </div>

                  <button class="btn btn-outline-light btn-lg px-5 " style="margin-left:90px;" type="submit">Login</button>

    <!--              <div class="d-flex justify-content-center text-center mt-4 pt-1">-->
    <!--                <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>-->
    <!--                <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>-->
    <!--                <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>-->
    <!--              </div>-->
            </form>
            </div>

                  <div>
                    <p class="mb-0 ml-5">Don't have an account? <a href="{% url 'credentials:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                    </p>
                  </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock  %}

test_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container-fluid d-flex justify-content-center mt-5 mx-0  ">

      <table class="table table-striped table-dark  " style="width:600px;">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>

          </tr>
        </thead>
        <tbody>
        {% for user in users %}
          <tr>
            <th scope="row">{{user.id}}</th>
            <td>{{ user.username}}</td>
            <td>{{ user.first_name}}</td>
            <td>{{ user.last_name}}</td>
            <td>{{ user.email}}</td>
            <td><a class="btn btn-danger" href="{% url 'credentials:delete_user' user.id %}">Delete</a>
            <td><a class="btn btn-warning" href="{% url 'credentials:update_user' user.id %}">Update</a> </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
</div>

{% endblock %}

test_project/templates/update.html
{% extends 'base.html' %}
{% block content %}
<section>
  <div class="mt-4 mb-4"">
    <div class="container h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card text-dark" style="border-radius: 1rem; background-color:#E0A96D;" >
            <div class="card-body p-5">
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn btn-outline-light btn-block btn-lg gradient-custom-7 text-body" style="background-color:black;" type="submit">Confirm</button>
                </form>
                 </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

test_project/templates/welcomepage.html
{% extends 'credentials_base.html' %}
{% load static %}
{% block content %}
<section class="vh-100 ">
  <div class="container py-5">
    <div class="row  justify-content-center  h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card" style="border-radius: 1rem; background-color:#E0A96D; background-position: center;background-repeat: no-repeat; background-size: cover;">
          <div class="card-body  p-5 ">

            <div class="mb-md-5 mt-md-4 pb-5 ">

                  <h5 class="fw-bold mb-2 ml-4 pl-5 text-dark text-uppercase" style="font-weight:900; "> HEAVEN'S STORE </h5>
                  <p class="mb-5 ml-5 text text-dark" style="font-weight:500;"><i>Welcome to shop in our store</i></p>
              <div class=" justify-content-center mt-0 pl-1 ml-4 mb-1">
                  <a href="{% url 'credentials:register' %}" class="btn btn btn-outline-light btn-block btn-lg gradient-custom-7 text-body" style="background-color:black; width:250px;">SIGN UP </a>
              </div>
              <div class=" justify-content-center  mt-0 pl-1 ml-4">
                   <a href="{% url 'credentials:login' %}" class="btn btn btn-outline-light btn-block btn-lg gradient-custom-7 " style="background-color:black;width:250px;">LOG IN </a>
              </div>
                <div class=" justify-content-center  mt-0 pl-1 ml-4">
                   <a href="{% url 'credentials:admin_login' %}" class="btn btn btn-outline-light btn-block btn-lg gradient-custom-7 " style="background-color:black;width:250px;">ADMIN </a>
              </div>
            </div>



          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock  %}